version: '3'

services:
  keycloak:
    image: jboss/keycloak:4.5.0.Final
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /var/keycloak/import/example-realm.json
    volumes:
      - ./keycloak/import/:/var/keycloak/import/:ro
    ports:
      - 8000:8080
  nginx:
    image: nginx:latest
    container_name: nginx
  app-cli:
    image: app-cli:latest
    container_name: app-cli
    build:
      context: ./app-cli/
    ports:
      - 80:80
  app-api:
    image: app-api:latest
    container_name: app-api
    extra_hosts:
      - "keycloak.example.org:${HOST_IP}"
    build:
      context: ./app-api
    ports:
      - 8080:8080


