version: '3'

services:

  keycloak:
    image: jboss/keycloak:4.5.0.Final
    container_name: identity-server
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /var/keycloak/import/example-realm.json
    volumes:
      - ./keycloak/import/:/var/keycloak/import/:ro

  reverse-proxy:
    image: reverse-proxy:latest
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy/
    restart: on-failure
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  app-cli:
    image: app-cli:latest
    container_name: app-cli
    build:
      context: ./app-cli/

  app-api:
    image: app-api:latest
    container_name: app-api
    extra_hosts:
      - "identity.example.org:${HOST_IP}"
    build:
      context: ./app-api


