FROM nginx:1.15.5

LABEL maintainer="Eric GEORGES <eric.georges@businessdecision.com>"

# see https://github.com/staticfloat/docker-nginx-certbot

COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl/ /etc/nginx/ssl/